# Generated by Django 6.0.6 on 2026-08-06 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0002_attendancerecord_device_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionFace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attendance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='session_face', to='attendance.attendancerecord')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_faces', to='attendance.attendancesession')),
            ],
            options={
                'indexes': [models.Index(fields=['session'], name='face_sessio_session_fce89d_idx')],
            },
        ),
    ]
