# Generated by Django 6.0.6 on 2026-08-06 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendancerecord_device_id'),
        ('face', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='sessionface',
            name='face_sessio_session_fce89d_idx',
        ),
        migrations.AlterField(
            model_name='sessionface',
            name='attendance',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='face', to='attendance.attendancerecord'),
        ),
        migrations.AlterField(
            model_name='sessionface',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faces', to='attendance.attendancesession'),
        ),
    ]
