# Generated by Django 6.0.6 on 2026-08-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0002_remove_sessionface_face_sessio_session_fce89d_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionface',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
