# Generated by Django 6.0.6 on 2026-07-15 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='device_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
